/**
 * Bootstrap wrapper generator for productive run.
 *
 * The CLI writes a temporary `.mjs` file that:
 *   1. Imports the Productive SDK using an absolute `file://` URL (no
 *      module-resolution setup required in the user's project directory).
 *   2. Imports the ScriptOutput factory from the CLI's own dist bundle.
 *   3. Creates a pre-configured client from PRODUCTIVE_* env vars.
 *   4. Exposes globals (`productive`, `output`, `args`) for pattern B scripts.
 *   5. Dynamically imports the user's script and calls its default export if
 *      it is a function (pattern A).
 */

export interface WrapperOptions {
  /** Absolute `file://` URL to the user's script. */
  scriptUrl: string;
  /** Absolute `file://` URL to `dist/script.js` (the CLI's output utilities + arg parser). */
  scriptOutputUrl: string;
  /** Absolute `file://` URL to the Productive SDK entry point. */
  sdkUrl: string;
  /**
   * Optional absolute `file://` URL to a resolver-hooks module (see
   * {@link generateResolverHooks}). When provided, it is registered via
   * `node:module`'s `register()` before the user script is imported, so the
   * script can `import` the `@studiometa/*` packages no matter where it lives.
   */
  hooksUrl?: string;
}

/**
 * Generate an ESM resolver-hooks module that maps a fixed set of bare
 * specifiers to absolute `file://` URLs.
 *
 * Registered via `node:module`'s `register()` in the wrapper, this lets a
 * `productive run` script `import` the `@studiometa/*` packages even when the
 * script file lives outside any `node_modules` tree (e.g. `~/Downloads`).
 * Unknown specifiers fall through to Node's default resolution.
 */
export function generateResolverHooks(importMap: Record<string, string>): string {
  return `// Auto-generated by \`productive run\` — do not edit.
const MAP = ${JSON.stringify(importMap, null, 2)};

export async function resolve(specifier, context, nextResolve) {
  if (Object.prototype.hasOwnProperty.call(MAP, specifier)) {
    return { url: MAP[specifier], shortCircuit: true };
  }
  return nextResolve(specifier, context);
}
`;
}

/**
 * Generate the wrapper `.mjs` source code.
 *
 * The returned string is a complete, self-contained ES module that can be
 * executed with `node [flags] wrapper.mjs`.
 */
export function generateWrapper(opts: WrapperOptions): string {
  const { scriptUrl, scriptOutputUrl, sdkUrl, hooksUrl } = opts;

  // Register resolver hooks so the user script can import the @studiometa/*
  // packages by bare specifier regardless of where the script file lives. The
  // register() call runs before the *dynamic* import of the user script below,
  // so the hooks are active for it. (The wrapper's own static imports are
  // hoisted and evaluated ahead of register(), but they use absolute URLs and
  // never need the hooks.)
  //
  // URLs are interpolated via JSON.stringify so a path containing characters
  // like a single quote can't break out of the generated string literal.
  const registerHooks = hooksUrl
    ? `import { register } from 'node:module';\nregister(${JSON.stringify(hooksUrl)}, import.meta.url);\n`
    : '';

  return `// Auto-generated by \`productive run\` — do not edit.
${registerHooks}import { Productive } from ${JSON.stringify(sdkUrl)};
import { createScriptOutput, parseScriptArgs, createDryRunFetch, printDryRunSummary } from ${JSON.stringify(scriptOutputUrl)};

const token = process.env.PRODUCTIVE_API_TOKEN;
const orgId = process.env.PRODUCTIVE_ORG_ID;
const userId = process.env.PRODUCTIVE_USER_ID ?? undefined;
const baseUrl = process.env.PRODUCTIVE_BASE_URL ?? undefined;
const dryRun = process.env.PRODUCTIVE_DRY_RUN === '1';

if (!token || !orgId) {
  console.error(
    '\\x1b[31m✗ productive run: PRODUCTIVE_API_TOKEN and PRODUCTIVE_ORG_ID must be set.\\x1b[0m\\n' +
    '  Configure credentials with: productive config set apiToken <token>',
  );
  process.exit(1);
}

const client = new Productive({ token, organizationId: orgId, userId, baseUrl });
const output = createScriptOutput();
const { args, flags } = parseScriptArgs(process.argv.slice(2));

// Dry-run mode: intercept mutating API calls via globalThis.fetch
const dryRunCalls = [];
if (dryRun) {
  globalThis.fetch = createDryRunFetch(dryRunCalls, globalThis.fetch);
}

// Pattern B globals
globalThis.productive = client;
globalThis.output = output;
globalThis.args = args;
globalThis.flags = flags;

// Import and execute the user script
const mod = await import(${JSON.stringify(scriptUrl)});

if (typeof mod.default === 'function') {
  // Pattern A: script exports a default async function
  await mod.default({ client, output, args, flags });
}
// Pattern B: script runs imperatively via globals — nothing more to do.

// Print dry-run summary after script completes
if (dryRun) {
  printDryRunSummary(dryRunCalls, output);
}
`;
}
