/**
 * Bootstrap wrapper generator for productive run.
 *
 * The CLI writes a temporary `.mjs` file that:
 *   1. Imports the Productive SDK using an absolute `file://` URL (no
 *      module-resolution setup required in the user's project directory).
 *   2. Imports the ScriptOutput factory from the CLI's own dist bundle.
 *   3. Creates a pre-configured client from PRODUCTIVE_* env vars.
 *   4. Exposes globals (`productive`, `output`, `args`) for pattern B scripts.
 *   5. Dynamically imports the user's script and calls its default export if
 *      it is a function (pattern A).
 */

export interface WrapperOptions {
  /** Absolute `file://` URL to the user's script. */
  scriptUrl: string;
  /** Absolute `file://` URL to `dist/script.js` (the CLI's output utilities). */
  scriptOutputUrl: string;
  /** Absolute `file://` URL to the Productive SDK entry point. */
  sdkUrl: string;
}

/**
 * Generate the wrapper `.mjs` source code.
 *
 * The returned string is a complete, self-contained ES module that can be
 * executed with `node [flags] wrapper.mjs`.
 */
export function generateWrapper(opts: WrapperOptions): string {
  const { scriptUrl, scriptOutputUrl, sdkUrl } = opts;

  return `// Auto-generated by \`productive run\` — do not edit.
import { Productive } from '${sdkUrl}';
import { createScriptOutput } from '${scriptOutputUrl}';

const token = process.env.PRODUCTIVE_API_TOKEN;
const orgId = process.env.PRODUCTIVE_ORG_ID;
const userId = process.env.PRODUCTIVE_USER_ID ?? undefined;
const baseUrl = process.env.PRODUCTIVE_BASE_URL ?? undefined;

if (!token || !orgId) {
  console.error(
    '\\x1b[31m✗ productive run: PRODUCTIVE_API_TOKEN and PRODUCTIVE_ORG_ID must be set.\\x1b[0m\\n' +
    '  Configure credentials with: productive config set apiToken <token>',
  );
  process.exit(1);
}

const client = new Productive({ token, organizationId: orgId, userId, baseUrl });
const output = createScriptOutput();
const args = process.argv.slice(2);

// Pattern B globals
globalThis.productive = client;
globalThis.output = output;
globalThis.args = args;

// Import and execute the user script
const mod = await import('${scriptUrl}');

if (typeof mod.default === 'function') {
  // Pattern A: script exports a default async function
  await mod.default({ client, output, args });
}
// Pattern B: script runs imperatively via globals — nothing more to do.
`;
}
